### ISSUE TITLE
nicht einrichtbar

### ISSUE THREAD

**Issue by TheMaikas** [EinfachAlex/Nimiq-Tipeeestream#1]
Beim Einrichten entsteht folgender Fehler trotz mehrmaligen "npm rebuild" und "npm install":
\\?\C:\Users\kekvin\Desktop\halt die fresse dummer spast\Client\node_modules\better-sqlite3\build\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

bitte fixxen danke

**Comment by EinfachAlex** [comment]
Lieber kekvin,
versuche es doch mal mit dem Befehl 

> **node_modules/.bin/electron-rebuild -f -w better-sqlite3**

**Comment by TheMaikas** [comment]
Danke für die Antwort. Ich gehe davon aus, dass das Problem behoben wurde und werde das Anliegen nun schließen.

**Comment by EinfachAlex** [comment]
Du sollst den Befehl eingeben was ist da behoben??? Es ist behoben wenn du Befehl eingeben net wenn du sagen iste behobe!

**Comment by lucsoft** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/a200e2ee-eece-4f55-b695-73bf58b26ee5-d2c9894d-9b28-4225-9efd-07510c2fd26e-v1.png?transparent=1&palette=1&width=246)

**Comment by lucsoft** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/3ea5fb70-e76c-4c70-99c8-c7ba6f2d9b5b-d2c9894d-9b28-4225-9efd-07510c2fd26e-v1.png?transparent=1&palette=1&width=246)
